
version: '3.8'

services:
  biamino-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    volumes:
      # Optional: mount logs directory
      - ./logs:/var/log/nginx
