// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wogargtqqsoqrxgwqpvc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndvZ2FyZ3RxcXNvcXJ4Z3dxcHZjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk3NjU2OTEsImV4cCI6MjA2NTM0MTY5MX0.vbIS50xHQzgPmNLbxEkkysszhK8_3zB8ggi5SDdTfew";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);